# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f24d61bdf882e808a90edb8f6b1a0f4ac01ab81596b2a49fea9fbbb43dab122fa4c70cffd31b4a91beb866029a467fdc0a620e0223187d1ac67f2df91ab686f

test:
  secret_key_base: c91569c69e23214174ce9ebbb1064278e0abfa24a0fac5635deea7e5880861491304c24a2ef330b16a34514abd6a7967f3795596b9756ef862fb7371c08a3051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
